export default {
	MORE_ABOUT_BLACKCOIN: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'MORE ABOUT BLACKCOIN' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ブラックコインの詳細` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	MORE_ABOUT_BLACKCOIN_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
		<p>
			Think of it like a <span>peoples bank</span>. Your
			<span>accounts cant be frozen</span>, it is completely and
			<span>always free</span>, it is <span>anonymous</span>, much
			<span>more secure</span> than traditional banking and
			<span>payments can be sent to anyone in the world within seconds</span>.
		</p>
		<p>
			Anyone can create an account just by downloading the software. This bank has no owners
			and cannot be shut down. Because it is <span>peer to peer</span>, it is
			<span>completely transparent</span>. There is a limited supply of coins making it
			valuable and a great store of wealth like gold. New coins can only be generated by the
			networks 1% rewards.
		</p>
		<p>So welcome to the <span>future of currency!</span></p>
		<p><span>Safe, fast, secure, anonymous, exciting and most of all fun!</span></p>
		<p>Here are some other accomplishments or honorable mentions:</p>
		<p>
			-Blackcoin was the <span>first coin to go full proof of stake.</span><br />
			-It is also the worlds <span>first coin to have working smart contracts.</span><br />
			-In early 2014 Blackcoin was the
			<span>first coin to combine POS with a multipool.</span>
			It was so powerful it was nicknamed the "Blackhole".<br />
			-Blackcoin was the
			<span>first coin to crowdfund and hire an advertising/PR agency Max Bourges!</span><br
			/>
			-Blackcoin is known for <span>having an outstanding community.</span>
			Everyone is a star here at Blackcoin. They have all worked tirelessly to make this coin one
			of actions instead of words. It is <span>one of the most active communities</span> next to
			Dogecoin.
		</p>
		<style>span {color: goldenrod;}</style>` /*English*/, 
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `<p>Blackcoin(ブラックコイン)のシステム、これは、個人銀行のようなものだと思ってください。簡単に口座は凍結される事無く、安心完全かつ常に無料で、匿名性が高く、従来の銀行よりもはるかに安全で、送金は世界中の誰にでも数秒で安全に送ることができます。</p>
		<p>ソフトウェアをダウンロードするだけで、誰でもアカウントを作成することができます。この銀行には所有者がおらず、閉鎖することもできません。ピア・ツー・ピアの為に高い透明性を有します。またブラックコインの発行枚数は有限です。その為ゴールドのように価値を維持し、富の保存場所としても最適です。新規発行されるBlackcoinは、ネットワークの1％の報酬によってのみ生成されます。</p>
		<p>未来の通貨へようこそ‼︎</p>
		<p>安全、迅速、セキュア、匿名、エキサイティング、そして何よりも楽しい！</p>
		<p>(Blackcoinの歴史や業績をご紹介します。)</p>
		<p>-Blackcoinは完全なプルーフオブステークを実現した世界で最初のコインです。</p>
		<p>-Blackcoinは世界で初めてスマートコントラクトを実現したコインでもあります。</p>
		<p>-2014年初頭、BlackcoinはPOSとマルチプールを組</p>
		<p>み合わせた最初のコインでした。それらの仕組みが、非常に強力であった為に、人々はこのコインを「ブラックホール」というニックネームを付けました。</p>
		<p>-Blackcoinは、クラウドファンディング上で広告・PR代理店のマックス・ブールジュを雇った最初のコインです。</p>
		<p>-古くからBlackcoinは優れたコミュニティを持つことで知られているます。このBlackcoinコミュニティでは、みんながリーダーです。コミュニティの皆さんは、このコインを言葉ではなく行動のコインにするために、日々、たゆまぬ努力を続けています。Dogecoinに次いで最も活発なコミュニティの一つでも有ります。</p>
		` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	
	HOW_DOES_IT_WORK: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'HOW DOES IT WORK?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ブラックコインの仕組み` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	HOW_DOES_IT_WORK_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
		<p>
			Did you know that in the United States that cryptocurrency is considered a commodity? So
			this means you get incredible tax breaks! Also many countries do not even tax it. Many
			people think smart contracts are the future! This is like the dawn of the internet.
		</p>
		<p>
			<span>Money will never be the same again</span>. So how does this work?
		</p>
		<p>
			The ability to manage transactions and issue additional BlackCoins is all handled by the
			network of users utilizing BlackCoin. <br />
			So this means <span>YOU are the banker</span>. Because the
			<span>BlackCoin network is run by the people</span>, holders of BlackCoin,
			<span>who receive a 1% yearly reward through a process called staking</span>.<br />
			BlackCoin is <span>open-source</span> too, meaning that the software that makes it
			function is completely available for public scrutiny giving you peace of mind.
			<span>No one owns BlackCoin</span>, it is not a single entity;
			<span>anyone can be a part of it</span>. The bank history is also called a "Blockchain".
			This history is shared by everyone. So when you download the program you save a copy of
			the history and share it! In addition you will stake while the software is running and
			make sure the bank history is secure. So it is <span>impossible to counterfeit</span>.
			Your account is a collection of keys. You can use those keys to sign transactions and
			evencontracts! Nobody else in the world has a copy of those keys, only you. So it is
			<span>impossible to forge your digital signature</span>. Thanks to the brilliant
			combination of digital signatures and torrents, cryptocurrency has risen to popularity.
		</p>
		<p>So to summarize:</p>
		<p>
			&#8211;<span>Everyone gets paid to keep the network secure</span><br />
			-Everyone shares the bank history, so <span>its transparent</span><br />
			-The software is open source so you know <span>its safe</span><br />
			&#8211;<span>It is anonymous</span> and anyone can open an account<br />
			&#8211;<span>It is extremely fast</span>, you can send money to anyone in the world
			within minutes<br />
			&#8211;<span>It is</span> and will always BE
			<span>FREE.</span>
		</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>取引管理やBlackCoinを新規発行する機能は、すべてBlackCoinを利用するユーザーネットワークが補います。</p>
			<p>つまり、BlackCoinを所有する、あなた自身が銀行家の役割を行えます。その意味は、BlackCoinのネットワークは、ステークと呼ばれるプロセスを通じて年に1％の報酬を受け取るBlackCoinの保有者である人々によって運営されている為です。</p>
			<p>BlackCoinはオープンソースです。つまり、BlackCoinを機能させているソフトウェアは完全に公開されており、安心して利用できます。また、BlackCoinの仕組みは、非中央集権的で、誰もが参加できる単一の仕組みです。</p>
			<p>一般的に、この様な銀行の取引履歴の仕組みは「ブロックチェーン」と呼ばれます。この履歴は誰もが共有しています。つまり、プログラムをダウンロードすると、履歴のコピーが保存され、それを共有することになるのです。さらにあなたのソフトウェアが作動している間にステークを行い、その銀行の取引履歴が安全であることを確認しています。ですので、銀行の取引履歴を偽造することは不可能です。また、あなたの所有するアカウント自体が、暗号鍵の集合体です。その鍵を使って、取引や契約に署名することができるのです。その鍵のコピーを持っているのは、世界中であなただけです。そのため、あなたのデジタル署名を他者が、偽造することは不可能です。デジタル署名とトレントの見事に組み合わせた技術で、暗号通貨は強固な取引信用を構築しています。</p>
			<p>(要約すると)</p>
			<p>-誰もがこのネットワークの安全性を保ちつつ報酬を得る。</p>
			<p>-誰もが銀行の履歴を共有しているので、透明性がある。</p>
			<p>-ソフトウェアはオープンソースなので、安全であることがわかる</p>
			<p>-誰でも簡単にアカウントを開設できます。</p>
			<p>-匿名性高く非常に高速で、数分以内に世界中の誰にでもお金を送ることができます。</p>
			<p>-今も昔もずーっと無料で使えます。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	BLACKCOIN_VS_BITCOIN: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'BLACKCOIN VS BITCOIN' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ブラックコインとビットコインの比較` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	BLACKCOIN_VS_BITCOIN_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
		<p>
			So <span>what makes Blackcoin so different from Bitcoin?</span>
		</p>
		<p>
			We love Bitcoin however we also seek to improve on it.
			<span
				>Because Bitcoin is so big, it takes too much time for people to agree on innovative
				changes</span
			>. This is why there was a huge surge in alternative currencies last few years. This has
			paved the way for Blackcoin.<br />
			<span>Blackcoin</span> has continued to lead the way in blockchain innovation. <br />
			The coin itself
			<span>has been forked from Github more than any other coin in the world!</span>
			It was started by Rat4 who worked on mostly POS(Proof of Stake) innovations. Rat4 wanted
			to prove that staking could be
			<span
				>secure and more efficient than Bitcoins old fashioned and expensive Proof of Work</span
			>.
		</p>
		<p>
			Several members of the community combined the fast POS with a mining pool to help
			support the market price and volume by applying upward pressure and this resulted in a
			huge rise in Blackcoins popularity. Later Rat4 was joined by David Zimbeck the sole
			creator of
			<span>BlackHalo</span> who was an active community member. David who was previously well
			known in other fields such as Chess and Entertainment taught himself Python and coded a
			'Smart Contracting' platform called BitHalo. Because he believed in Rat4 and agreed with
			the security of Blackcoin and the Multipool innovations, David chose to debut Halo in
			Blackcoin. Because of this,
			<span
				>Blackcoin was an entire year ahead of other Smart Contracting proposals such as
				Etherium</span
			>. Rat4 then took to making proof of stake more secure by forcing users to interact more
			with the network and to eliminate some of the security flaws. So he created
			<span>Proof of Stake 2.0</span>. In 2015, Rat4 has started working on a 3.0 protocol to
			finally master the protocol. In the meantime, David released a Decentralized Marketplace
			and Decentralized Servers and greatly improved BlackHalo giving it tons of new and
			exciting features focused on user friendliness. All of this was to prepare the coin for
			the arrival of a
			<span>Decentralized Exchange built solely on Blackcoin</span>. Since then, many other
			developers have contributed. Drunkonsound, a community member, built and sponsored the
			exco.in exchange as well as several other Blackcoin projects. The exco.in exchange was
			the first exchange to have live, high frequency trading and built with lots of great
			charting and features for trading. Again Blackcoin grew and a new project, Legionairre
			was also started by a community member, btclaw. Legionairre gives people the ability to
			have <span>Stealth Addresses</span>. Their primary focus is your privacy. The momentum
			in Blackcoin has been continuing and
			<span>every year more new and exciting features are being added</span>.
		</p>
		<p>
			The best part is, if you get involved you can be part of all of the excitement of
			<span>the future of the internet</span>.
		</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>では、Blackcoinはビットコインと何が違うのでしょうか？</p>
			<p>私たちはビットコインを愛していますが、同時にビットコインを改善しようとしています。ビットコインは非常に大きいので、革新的な変化に人々が同意するには時間がかかりすぎます。そのため、ここ数年で代替通貨が急増しています。これがブラックコインへの道を開いたのです。</p>
			<p>ブラックコインは、ブロックチェーンの革新をリードし続けてきました。</p>
			<p>このコイン自体が、世界のどのコインよりもGithubからフォークされています 主にPOS（Proof of Stake）のイノベーションに取り組んでいたRat4が始めたものです。Rat4は、Bitcoinの旧式で高価なProof of Workよりも、ステークが安全で効率的であることを証明したかったのです。</p>
			<p>コミュニティの何人かのメンバーは、この高速POSとマイニングプールを組み合わせて、市場の価格と量に上昇圧力をかけてサポートし、その結果、ブラックコインの人気は大きく上昇しました。その後、Rat4には、BlackHaloの唯一の作者であり、活発なコミュニティメンバーであったDavid Zimbeckが加わりました。チェスやエンターテイメントなどの分野で有名だったデビッドは、独学でPythonを学び、BitHaloという「スマートコントラクト」プラットフォームをコーディングしました。Rat4を信じ、ブラックコインの安全性とマルチプールの革新性に賛同していたデビッドは、ブラックコインでHaloをデビューさせることを選択しました。このおかげで、ブラックコインはEtheriumなどの他のスマートコントラクト提案よりも丸1年先を行くことができました。Rat4はその後、ユーザーにネットワークとの対話を強いることでプルーフ・オブ・ステークの安全性を高め、セキュリティ上の欠陥を解消することに取り組んだ。そこで彼はProof of Stake 2.0を作成しました。2015年、Rat4は最終的にプロトコルをマスターするために、3.0のプロトコルに取り組み始めました。その間に、デビッドは分散型マーケットプレイスと分散型サーバーをリリースし、BlackHaloを大幅に改良して、ユーザーの利便性に焦点を当てた大量の新しいエキサイティングな機能を与えました。これらはすべて、ブラックコインのみで構築された分散型取引所の到来に備えたものでした。それ以来、他の多くの開発者が貢献しています。コミュニティのメンバーであるDrunkonsoundは、exco.inの取引所や他のいくつかのBlackcoinプロジェクトを構築し、後援しました。exco.inの取引所は、ライブの高頻度取引を行った最初の取引所であり、取引のための優れたチャートや機能をたくさん備えていました。再びBlackcoinが成長し、新しいプロジェクトであるLegionairreもコミュニティメンバーのbtclaw氏によって開始されました。Legionairreは、人々にステルスアドレスを提供します。彼らが最も重視しているのは、あなたのプライバシーです。ブラックコインの勢いはとどまるところを知らず、年々、新しいエキサイティングな機能が追加されています。</p>
			<p>一番の魅力は、あなたが参加すれば、インターネットの未来の興奮のすべてに参加できるということです。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	
	PROOF_OF_STAKE_VS_PROOF_OF_WORK: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'PROOF OF STAKE VS PROOF OF WORK' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `POSとPOWの比較` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	PROOF_OF_STAKE_VS_PROOF_OF_WORK_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
		<p>
			Proof-of-Work was a fantastic innovation that formed the backbone of the original
			Bitcoin protocol. The idea is that by solving a computationally intensive math problem,
			one can prove the effort they've done to secure the protocol. This is how a blockchain
			is generated, and the effort that is required to perform this computations contribute to
			a coin's scarcity and value.
		</p>
		<p>
			However, <span
				>Proof-of-Work eventually becomes an extraordinarily expensive system</span
			>.
		</p>
		<p>
			<span>Proof of Stake solves this issue</span> in a very elegant way. Rather than using
			computer power as a scarce resource to generate security, Proof of Stake uses the
			scarcity of the coin itself. A user may choose to
			<span>"stake" his coins to generate the next block in the chain</span>, and his chance
			of doing so is basically proportional to the weight of his own coins.
		</p>
		<p>
			BlackCoin was notably the first coin to use a Proof-of-Work creation cycle followed by
			transition to full Proof-of-stake. <br />
			<span
				>Proof-of-Stake is eco-friendly and efficient, and avoids the vast waste of energy and
				hardware overhead of Proof-of-Work based networks</span
			>.<br />
			Over time, BlackCoin's core protocol has made industry-leading improvements to Proof-of-Stake
			security and general functionality (PoS 2.0 and PoS 3.0).
		</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
		<p>Proof-of-Workは、オリジナルのBitcoinプロトコルのバックボーンを形成する素晴らしいイノベーションでした。計算量の多い数学の問題を解くことで、プロトコルの安全性を確保するために行った努力を証明することができるというものです。このようにしてブロックチェーンが生成され、この計算を行うために必要な労力がコインの希少性と価値に貢献します。</p>
	<p>しかし、Proof-of-Workは最終的に余計なコストがかかるシステムになってしまいます。</p>
	<p>Proof of Stakeは、この問題を非常にエレガントな方法で解決しています。Proof of Stakeは、セキュリティを生成するために希少資源であるコンピュータのパワーを利用するのではなく、コイン自体の希少性を利用しています。ユーザーは、チェーンの次のブロックを生成するために自分のコインを「賭ける」ことを選択でき、その確率は基本的に自分のコインの重さに比例します。</p>
	<p>BlackCoinは、Proof-of-Workの生成サイクルを採用した最初のコインであり、その後、完全なProof-of-Stakeに移行したことで注目を集めました。</p>
	<p>Proof-of-Stakeは環境に優しく効率的であり、Proof-of-Workベースのネットワークで発生する膨大なエネルギーの浪費やハードウェアのオーバーヘッドを回避することができます。</p>
	<p>BlackCoinのコアプロトコルは、Proof-of-Stakeのセキュリティと一般的な機能性について、時間をかけて業界をリードする改善を行ってきました（PoS 2.0およびPoS 3.0）。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	
	THE_ANNUAL_INFLATION_OF_BLACKCOIN: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'THE ANNUAL INFLATION OF BLACKCOIN' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `Blackcoinの年間インフレ率。` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	THE_ANNUAL_INFLATION_OF_BLACKCOIN_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
		<p>
			It is a fixed amount of BLK due to <span>static block reward</span>, and a slightly less
			inflation rate year on year because of that.
		</p>
		<p>
			The block time target is 67 seconds, so working that out per year (60/67 x 60) x 24 x
			365 is 470686 block rewards (1.5BLK) in a year which is <span
				>706,030 new BLK per year roughly.</span
			> As of right now, 706,030 is 1.172% of the total supply of 60,238,885 BLK.
		</p>
		<p>
			This 1.172% is distributed to only fraction of the shareholders, the ones who stake.
			<span
				>The reward rate is way above 1%, average to 4-8% annual depending on time and amount
				of BLK staked.</span
			>
		</p>
		<p>
			That means if only 20% of coins were being actively staked, you could actually get
			around 5%/year for continually staking, since 80% of people (avg) weren't staking and
			get nothing.
		</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
		<p>ブロックリワードが固定されているためにBLKの量が固定されており、そのために年々インフレ率が少しずつ低くなっています。</p>
		<p>ブロックタイムの目標は67秒なので、1年で計算すると（60/67×60）×24×365で470686ブロックリワード（1.5BLK）となり、大体1年で706,030個のBLKが新たに手に入ることになります。現在のところ、706,030は総供給量60,238,885BLKの1.172%にあたります。</p>
		<p>この1.172%は、出資した株主の一部にしか分配されません。報酬率は1％をはるかに超えており、時間と賭けたBLKの量に応じて平均で年4～8％になります。</p>
		<p>つまり、20％のコインだけが積極的に賭けられていたとしたら、80％の人（平均）が賭けずに何も得られないので、継続的に賭けることで実際には年5％程度を得ることができるのです。</p>
		` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	
	WHERE_CAN_I_CHECK_THE_NETWORK_WEIGHT: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'WHERE CAN I CHECK THE NETWORK WEIGHT?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ネットワークウェイトの確認方法は？` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHERE_CAN_I_CHECK_THE_NETWORK_WEIGHT_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
		<p>
			You can check the network weight on the <span>bottom right of your wallet</span>.<br /> or
			by running the getstakinginfo command from the debug console. Network weight is computed
			from the last 72 blocks.
		</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>ウォレットの右下部でネットワークウェイトを確認することができます。</p>
			<p>または、デバッグコンソールからgetstakinginfoコマンドを実行することで確認できます。ネットワークウェイトは直近の72ブロックから計算出来ます。</p>
		` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHERE_CAN_I_BUY_BLACKCOIN: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'WHERE CAN I BUY BLACKCOIN?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `BLACKCOINは何処で買えるのですか？` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHERE_CAN_I_BUY_BLACKCOIN_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
			<p>
				You can purchase BlackCoins on different <span>online exchanges</span>.<br />
			</p>
			<p>
				You could find exchanges with the greatest volume at
				<a
					href="https://coinmarketcap.com/currencies/blackcoin/#markets"
					target="_blank norefer">Coinmarketcap.com/Markets</a
				>
			</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>BlackCoinsは、さまざまなオンライン取引所で購入できます。</p>
			<p>最新の最も取引量の多い取引所の情報はCoinmarketcap.com</p>
			<p>(コインマーケットキャップで検索)で確認できます。</p>
			<p>コイン検索(BLACKCOINまたはBLK)-中段左上の(市場)を</p>
			<p>クリックすると、上段から最新の取引額大きい取引所から</p>
			<p>取引額低い順に、取引所の名前が出ます。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	
	STAKING: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'STAKING' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ステイキング` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	STAKING_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
			<p>
				Blackcoin is a pure PoS (Proof-of-Stake) coin and can no longer be mined in the usual
				way. However, you can still mine by what is called <span>Staking</span>. This also
				serves to
				<span>secure the network</span> and aid in the various transactions made for all
				Blackcoin users.
				<span
					>Staking will earn you from 1% to 8% (depend on the network weight) of your total
					amount of coins held in your wallet over the period of a year</span
				>, and will start as soon as you have unlocked your wallet.
			</p>
			<p>
				Once you start to Stake, you will notice that a certain amount of coins will be placed
				into your Stake balance (you can see this under the Overview tab on your wallet) and
				those coins will begin to stake.
				<span>The more coins you have, the more coins you will earn by Staking.</span>
			</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>ブラックコインは純粋なPoS（Proof-of-Stake）コインであり、通常の方法ではマイニングできなくなりました。しかし、ステーキングと呼ばれる方法で採掘することは可能です。ステーキングは、ネットワークの安全性を確保し、ブラックコインユーザーの様々な取引を支援する役割も果たします。Stakingを行うと、1年間でウォレットに保有しているコインの総量の1%から8%(ネットワークの重さによって異なる)を獲得することができ、ウォレットのロックを解除するとすぐに開始されます。</p>
			<p>ステイクを開始すると、一定量のコインがステイク残高に入り（ウォレットの「概要」タブで確認できます）、そのコインがステイクを開始します。コインが多ければ多いほど、ステイクによって獲得できるコインも多くなります。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHAT_KIND_OF_COMPUTING_POWER_IS_REQUIRED_FOR_STAKING: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'WHAT KIND OF COMPUTING POWER IS REQUIRED FOR STAKING?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ステイキングに必要な計算能力は？` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHAT_KIND_OF_COMPUTING_POWER_IS_REQUIRED_FOR_STAKING_ANSWER: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
			<p>
				Staking doesn't need to do a lot of work, so the <span
					>requirements are incredibly small</span
				>.<br />
				You would have a hard time to find a computer today that is NOT able to stake.
			</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `<p>ステイキングは多くの作業を必要としませんので、必要条件は驚くほど小さいのです。その為、現在のコンピュータで、ステーキングができないものを探すのは難しいでしょう。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	HOW_BIG_ARE_BLOCK_REWARDS: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'HOW BIG ARE BLOCK REWARDS?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ブロック報酬の大きさは？` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	HOW_BIG_ARE_BLOCK_REWARDS_ANSWER: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
			<p>
				You get <span>1.5 BLK reward + any tx fees in that block</span>.
			</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>1.5BLK分の報酬とそのブロック内のTx料金を得ることができます。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	HOW_OFTEN_WILL_I_RECEIVE_A_BLOCK_REWARD: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'HOW OFTEN WILL I RECEIVE A BLOCK REWARD?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `どのくらいの頻度でブロックリワードを受け取ることができますか？` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	HOW_OFTEN_WILL_I_RECEIVE_A_BLOCK_REWARD_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
			<p>With 10000 BLK you can expect to stake around once a day (1.5BLK).</p>
			<p>
				There's no predicting exactly how many stakes you will get. However, <span
					>if you stake with more coins, you get more blocks and you more likely to find a
					reward</span
				>. Someone staking 24 hours a day, 365 days a year would get more (~24x) than someone
				staking the same amount of coins an hour a day.
			</p>
			<p>
				Staking is a kind of lottery. Some days you'll get more than usual, some days less. It's
				just an estimate.
			</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
			<p>10000BLKであれば、1日1回（1.5BLK）程度の出目が期待できます。</p>
			<p>賭け金が何回になるかは正確には予測できません。しかし、より多くのコインを賭けていれば、より多くのブロックを得ることができ、より多くの報酬を見つけることができます。1年365日、1日24時間賭けている人は、1日1時間、同じ量のコインを賭けている人よりも多く（～24倍）の報酬を得ることができます。</p>
			<p>ステーキングは一種の宝くじです。いつもより多くもらえる日もあれば、</p>
			<p>少ない日もあるでしょう。あくまでも目安ですが。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHAT_ARE_THE_OFFICIAL_BLACKCOIN_WEBSITES: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: 'WHAT ARE THE OFFICIAL BLACKCOIN WEBSITES?' /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `ブラックコインの公式サイトはどこですか？` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	WHAT_ARE_THE_OFFICIAL_BLACKCOIN_WEBSITES_ANSWER1: {
		zh: `` /*Chinese*/,
		es: `` /*Spanish*/,
		en: `
			<p>
				<a href="https://blackcoin.org/" target="_blank norefer">https://blackcoin.org</a> -
				<a href="https://blackcoinmore.org/" target="_blank norefer"
					>https://blackcoinmore.org</a
				>
				- <a href="https://blackcoin.nl/" target="_blank norefer">https://blackcoin.nl</a> are
				<span>the only official Blackcoin websites</span>.<br />. Note: The domain blackcoin.io
				is used for Blacksight, PayBLK and Iris.
			</p>
			<p>DO NOT DOWNLOAD FROM OR SIGN UP TO ANY OTHER BLACKCOIN LOOK WEBSITE!</p>` /*English*/,
		hi: `` /*Hindi*/,
		ar: `` /*Arabic - Right-to-left*/,
		pt: `` /*Portuguese*/,
		bn: `` /*Bengal*/,
		ru: `` /*Russian*/,
		ja: `
		<p>https://blackcoin.org - https://blackcoinmore.org - https://blackcoin.nl は、唯一のブラックコイン公式サイトです。</p>
		<p>コインマーケットキャップのBlack Coinページの上方左側の(ウエブサイト)の項目からもBlack Coin公式サイトを開けます。</p>
		<p>注意)現在、blackcoin.ioというドメインは、Blacksight、PayBLK、Iris</p>
		<p>に使用されています。他には、Blackcoin 非公式なウェブサイトからダウンロードしたり、登録したりしないでください。</p>` /*Japanese*/,
		jv: `` /*Javanese*/,
		de: `` /*German*/,
		ko: `` /*Korean*/,
		fr: `` /*French*/,
		te: `` /*Telugu*/,
		mr: `` /*Marathi*/,
		tr: `` /*Turkish*/,
		ta: `` /*Tamil*/,
		vi: `` /*Vietnamese*/,
		ur: `` /*Urdu - Right-to-left*/,
		nl: `` /*Dutch*/,
		it: `` /*Italian*/,
		hr: `` /*Croatian*/
	},
	
};
