export default {
	HOW_LONG_DOES_THE_WALLET_TAKE_TO_SYNC: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'HOW LONG DOES THE WALLET TAKE TO SYNC?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットの同期にはどのくらいの時間がかかりますか？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_LONG_DOES_THE_WALLET_TAKE_TO_SYNC_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '現在のブートストラップは約2.0GBです。ダウンロードには長い時間を要する事があります（インターネットの速度と利用可能な条件によります。)' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_LONG_DOES_THE_WALLET_TAKE_TO_SYNC_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ブートストラップをダウンロードすることは、Blackcoin Legacyウォレットを使用する際の最初の同期を早めるのに良い方法です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_LONG_DOES_THE_WALLET_TAKE_TO_SYNC_ANSWER3: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'BLK Bootstrapは、ページの一番下（FAQ/OTHER/BOOTSTRAP）にあります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'WHY IS THE WALLET NOT SYNCING?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットが同期されないのはなぜですか？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '1. ウォレットのバージョンが最新であることを確認してください' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '2. ファイアウォールやアンチウィルスソフトがウォレットの接続をブロックしていないか確認してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER3: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '3. システムの時計が正確であることを確認してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER4: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '4. コインが成熟するには約8時間（～501ブロック）かかります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER5: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットは自分のピアサークルを作ります。それには時間がかかります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER6: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'しかし、あなたはノードのリストを与えることでウォレットを助けることができます。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER7: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'addnodeを適用するには、blackcoin.conf (Legacy)またはblackmore.conf (More)を見つける必要があります。それはここにあるはずです。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER8: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'Windows: %APPDATA%\\blackcoin\\' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER9: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'or %APPDATA%\\blackmore\\' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER10: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'Linux： $HOME/.blackcoin/' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER11: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'または $HOME/.blackmore/' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER12: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'Mac OSX： $HOME/Library/Application Support/blackcoin/ (日本語)' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER13: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'または $HOME/Library/Application Support/blackmore/ です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER14: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '次に、https://chainz.cryptoid.info/blk/#！ネットワークにアクセスします。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER15: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '"ノードリスト "をクリックしてください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER16: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'リスト全体を.confの最後にコピーします。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER17: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ブラックコインの起動 ' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER18: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '* OSはファイルの拡張子を隠すことがあるので、.confが実際には.conf.txtではないことを確認してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER19: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'それでも問題が解決しない場合は、debug.logをチェックしてエラーを探し、Blackcoin Discordで質問してください https://discord.com/invite/hjNUgWD)' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHY_IS_WALLET_NOT_SYNCING_ANSWER20: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '何をするにしても、wallet.datをバックアップしてください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'HOW TO SEND BLACKCOIN?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ブラックコインを送るには？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'コインを送る方法はとても簡単です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'コインを友人、取引所、企業などに送る場合、必要なのは相手の受信アドレス（取引所では入金アドレスとして知られています）です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER3: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'お使いのウォレットが暗号化されている場合は、パスフレーズ（暗号化フレーズ）も必要です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER4: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '支払い先 友人や取引所、会社のBlackcoinアドレスを入力します。これらのアドレスは、内蔵のアドレス帳にも保存され、いつでもラベル付けや再ラベル付けができます）。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER5: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ラベルを付ける。Bittrexなどの取引所に送る場合は、「Bittrex exchange」と入力してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER6: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'Amount（金額）。送付する金額。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER7: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'コインをアドレスに送る場合は、アドレスを入力するのではなく、コピーしてPay Toエリアに貼り付けると、誤ったアドレスを入力することを防ぐことができます。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_SEND_BLACKCOIN_ANSWER8: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '(コピーアンドペースト)' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'HOW TO RECEIVE BLACKCOINS?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ブラックコインを受け取るには？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'コインを送るのと同様に、コインを受け取るのも簡単です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'BlackCoinsを取引所で購入した場合や、BLKで支払いを受けた場合は、コインを自分のウォレットに直接送信するための受信アドレスが必要になります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS_ANSWER3: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'デフォルトでは、受信アドレスは1つしかありませんので、そのアドレスを右クリックして「アドレスをコピー」を選択してください。これで、手動で入力してエラーになるのを防ぐことができます。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS_ANSWER4: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'そのアドレスを、支払い（または交換）したい人に渡してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS_ANSWER5: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '新しいアドレスを作るのはとても簡単なので、取引のたびに同じアドレスを使ってコインを受け取る必要はありません。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_RECEIVE_BLACKCOINS_ANSWER6: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '下部にある「新しいアドレス」をクリックして、好きなラベルを付けてください。（例：サイトからの寄付）そうすれば、個々の取引を簡単に確認することができます。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_OPEN_YOUR_WALLET_FOR_STAKING: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'HOW TO OPEN YOUR WALLET FOR STAKING?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ステーキングのために財布を開くには？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_OPEN_YOUR_WALLET_FOR_STAKING_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'Wallet Settings > Unlock Wallet' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_OPEN_YOUR_WALLET_FOR_STAKING_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレット設定＞ウォレットのロック解除' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHAT_IS_THE_MAX_AMOUNT_OF_NETWORK_CONNECTIONS: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'WHAT IS THE MAX AMOUNT OF NETWORK CONNECTIONS?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ネットワーク接続の最大数は？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHAT_IS_THE_MAX_AMOUNT_OF_NETWORK_CONNECTIONS_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'アウトバウンド接続の上限は最大16です。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHAT_IS_THE_MAX_AMOUNT_OF_NETWORK_CONNECTIONS_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'それ以上の接続数が必要な場合は、インバウンド接続を受け入れる必要があります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	WHAT_IS_THE_MAX_AMOUNT_OF_NETWORK_CONNECTIONS_ANSWER3: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットはポート15714をリッスンします。そのポートがブロックされていないか確認してください。また、他のピアがあなたのノードを発見して接続するまでに時間がかかります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	UPGRADING_WALLET: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'UPGRADING WALLET' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットのアップグレード' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	UPGRADING_WALLET_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '古いバイナリを新しいバイナリに置き換えるだけです。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	UPGRADING_WALLET_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'アップグレードする前に、wallet.datファイルの最新のバックアップがあることを確認してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	CHANGING_WALLET_LOCATION: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'CHANGING WALLET LOCATION' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットの位置変更' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	CHANGING_WALLET_LOCATION_ANSWER: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'blackcoin-qt.exe -datadir=NEW LOCATION を実行するショートカットを作成します。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_OFTEN_DO_I_NEED_TO_BACKUP_MY_WALLET: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'HOW OFTEN DO I NEED TO BACKUP MY WALLET?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'どのくらいの頻度でウォレットをバックアップする必要がありますか？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_OFTEN_DO_I_NEED_TO_BACKUP_MY_WALLET_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットから他のアドレスにコインを送信する場合は、送信することで新たにアドレスが変更される可能性があるため、バックアップを取る必要があります。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_OFTEN_DO_I_NEED_TO_BACKUP_MY_WALLET_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '同じアドレスにステイクしてコインを受け取る以外のことをしていないのであれば、おそらく追加のバックアップを作成する必要はありません。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_STOP_STAKING_TO_BE_ABLE_TO_SEND_COINS: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'HOW TO STOP STAKING TO BE ABLE TO SEND COINS?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'コインを送れるようにするには、どのようにしてstakingを止めるのでしょうか？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_STOP_STAKING_TO_BE_ABLE_TO_SEND_COINS_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '501回の確認を経て、ステークしていたお客様の残高が解放されます。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	HOW_TO_STOP_STAKING_TO_BE_ABLE_TO_SEND_COINS_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'トランザクションタブで進捗状況を確認することができます。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	SENDING_BLACKCOINS_FROM_CERTAIN_ADDRESS: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'SENDING BLACKCOINS FROM CERTAIN ADDRESS' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '特定のアドレスからブラックコインを送金する' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	SENDING_BLACKCOINS_FROM_CERTAIN_ADDRESS_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウォレットにいくつかのアドレスを作成したが、BlackCoinsの送信先を特定のアドレスにしたい場合。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	SENDING_BLACKCOINS_FROM_CERTAIN_ADDRESS_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '設定」→「オプション」→「表示」→「コインコントロール機能の表示を確認」→「適用」。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	SENDING_BLACKCOINS_FROM_CERTAIN_ADDRESS_ANSWER3: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: '送信 >> 入力 >> "チェック" 送信したいアドレスを選択してください。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	DOES_A_WEB_OR_MOBILE_WALLET_EXIST: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: 'DOES A WEB OR MOBILE WALLET EXIST?' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウェブやモバイルのウォレットは有りますか？' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	DOES_A_WEB_OR_MOBILE_WALLET_EXIST_ANSWER1: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'はい、PayBLKは使いやすく、オープンソースで、マルチプラットフォーム（7つのプラットフォームをサポート）で、マルチシグネチャで、個人と企業の両方に安全なブラックコインウォレットプラットフォームです。' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	},
	DOES_A_WEB_OR_MOBILE_WALLET_EXIST_ANSWER2: {
		zh: '' /*Chinese*/,
		es: '' /*Spanish*/,
		en: '' /*English*/,
		hi: '' /*Hindi*/,
		ar: '' /*Arabic - Right-to-left*/,
		pt: '' /*Portuguese*/,
		bn: '' /*Bengal*/,
		ru: '' /*Russian*/,
		ja: 'ウェブでは PayBLK.BlackCoin.io' /*Japanese*/,
		jv: '' /*Javanese*/,
		de: '' /*German*/,
		ko: '' /*Korean*/,
		fr: '' /*French*/,
		te: '' /*Telugu*/,
		mr: '' /*Marathi*/,
		tr: '' /*Turkish*/,
		ta: '' /*Tamil*/,
		vi: '' /*Vietnamese*/,
		ur: '' /*Urdu - Right-to-left*/,
		nl: '' /*Dutch*/,
		it: '' /*Italian*/,
		hr: '' /*Croatian*/
	}
};
